title: Nguyen Cao # your name (or website title) here
logo: "/images/pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring data scientist with a considerable experience in environmental science, project management, and working in diverse and collaborative environments.
  <br><br>
  7-year Volunteer Staff and Senior Staff Member for the National Model United Nations
  <br><br>
  Doctoral Candidate in Environmental Science at the University of Texas at Arlington
  <br><br>
  <a href="https://www.linkedin.com/in/nguyenhcao">View My LinkedIn Profile</a> <br><br>
  <a href="https://github.com/ngcao">View My Github Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
