title: Nguyen Cao # your name here
logo: "/images/pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  
  Aspiring data scientist with a considerable experience in environmental science, project management, and working in diverse and collaborative environments.
  <br><br>
  
  7-year Volunteer Staff and Senior Staff Member for the National Model United Nations.
  <br><br>
  
  Doctoral Candidate in Environmental Science at the University of Texas at Arlington.
  <br><br>
  
  Technical Skills <br><br>
  - Machine Learning <br><br>
  - Statitistics and Probability <br><br>
  - Data Visualization <br><br>
  - R, Python, SQL, and Tableau <br><br>
  
  Certificates <br><br>
  - EdX       - The Analytics Edge <br><br>
  - Udaticy   - Data Analyst Nanodegree <br><br>
  - Dataquest - Data Scientist Path <br><br>
  
  Packages <br><br>
  - (Python) Numpy, Pandas, Matplotlib, Seaborn, Scikit-learn, Statsmodels <br><br>
  - (R)      Tidyverse, parsnip, glmnet, rpart, ranger, xgboost, kernlab <br><br>
  
  <a href="https://www.linkedin.com/in/nguyenhcao">View My LinkedIn Profile</a> <br><br>
  <a href="https://www.dropbox.com/s/krw5ew0lgivttma/Cao%2C%20Nguyen_resume.pdf?dl=0">View My Resume</a> <br><br>





theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
